### PR TITLE
refactor: move eslintIgnore to package.json

### PR DESCRIPTION
**Pull request by safaiyeh**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by safaiyeh** [comment]
Oh cool, it was generated when I used it. Tried with the latest and it is all good now. Thanks!

**Comment by satya164** [comment]
Maybe we can move it to `package.json` regardless. I thought that it was not possible to have it in `package.json` 😅

**Comment by safaiyeh** [comment]
Alright! I'll move it over, I'll update this tonight

**Comment by safaiyeh** [comment]
@satya164 updated!

**Pull request merged**
